apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caddy-ingress-controller.name" . }}-configmap
  namespace: {{ .Release.Namespace }}
data:
{{- range keys .Values.ingressController.config | sortAlpha }}
  {{ . }}: {{ get $.Values.ingressController.config . | quote }}
{{- end }}

