before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/caddy
    binary: ingress-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "caddy/ingress:test-image"
    use: buildx
    dockerfile: Dockerfile
    skip_push: "true"
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "caddy/ingress:{{ .Tag }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "caddy/ingress:{{ .Tag }}-arm64v8"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"

docker_manifests:
  - name_template: "caddy/ingress:{{ .Tag }}"
    image_templates:
      - "caddy/ingress:{{ .Tag }}-amd64"
      - "caddy/ingress:{{ .Tag }}-arm64v8"

release:
  disable: true