apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
  - image: docker.io/mavimo/caddy-ingress-controller
deploy:
  helm:
    releases:
    - name: caddy-ingress-development
      namespace: caddy-system
      chartPath: kubernetes/charts/caddyingresscontroller
      recreatePods: true
      values:
        image: docker.io/mavimo/caddy-ingress-controller
portForward:
- resourceType: service
  resourceName: caddy-ingress-controller
  namespace: caddy-system
  address: 0.0.0.0
  port: 80
  localPort: 80
- resourceType: service
  resourceName: caddy-ingress-controller
  namespace: caddy-system
  address: 0.0.0.0
  port: 443
  localPort: 443
