apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: gcr.io/danny-239313/ingresscontroller
deploy:
  kubectl:
    manifests:
    - hack/test/example-deployment.yaml
    - hack/test/example-ingress.yaml
    - hack/test/example-deployment2.yaml
    - hack/test/example-service2.yaml
    - hack/test/example-service.yaml
    - kubernetes/generated/clusterrole.yaml
    - kubernetes/generated/clusterrolebinding.yaml
    - kubernetes/generated/deployment.yaml
    - kubernetes/generated/serviceaccount.yaml
    # - kubernetes/generated/loadbalancer.yaml
