{{- if .Values.ingressController.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "caddy-ingress-controller.name" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
      - "networking.k8s.io"
    resources:
      - ingresses
      - ingresses/status
      - secrets
    verbs: ["*"]
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - nodes
      - routes
      - extensions
    verbs:
      - list
      - get
      - watch
{{- end }}
