{{- if .Values.minikube }}
# we don't need a loadbalancer for local deployment purposes
{{ else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "caddy-ingress-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "caddy-ingress-controller.labels" . | nindent 4 }}
spec:
  type: "LoadBalancer"
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "caddy-ingress-controller.selectorLabels" . | nindent 4 }}
{{- end }}
