{{- if .Values.caddyingresscontroller.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "caddyingresscontroller.name" . }}-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "caddyingresscontroller.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "caddyingresscontroller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
